vim.keymap.set("n", "gi", vim.lsp.buf.implementation)
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "gr", vim.lsp.buf.references)
vim.keymap.set("n", "gh", vim.lsp.buf.hover)
vim.keymap.set("n", "gnr", vim.lsp.buf.rename)
vim.keymap.set("n", "ge", ":TroubleToggle <CR>")